- name: Prompt for user secret input
  ansible.builtin.pause:
    prompt: "{{ managed_user_secret }}:"
    echo: false
  register: user_input_result
  when: (managed_user_secret is defined) and (vars[managed_user_secret] | default('') | length == 0)

- name: Set secret input as fact
  ansible.builtin.set_fact:
    "{{ managed_user_secret }}": "{{ user_input_result.user_input }}"
  when: user_input_result is not skipped
