- name: List SSH keys in GitHub account using gh CLI
  ansible.builtin.command:
    cmd: "gh ssh-key list"
  register: ssh_key_list_result
  failed_when: "ssh_key_list_result.rc != 0"

- name: Read SSH public key
  ansible.builtin.slurp:
    src: "{{ ssh_public_key_file }}"
  register: ssh_key_content

- name: Check if SSH key is already added to GitHub
  ansible.builtin.set_fact:
    ssh_key_already_added: "{{ (ssh_key_content['content'] | b64decode) in ssh_key_list_result.stdout }}"

- name: Add SSH key to GitHub account using gh CLI
  ansible.builtin.command:
    cmd: "gh ssh-key add {{ ssh_public_key_file }} --title 'automation-added key'"
  register: ssh_key_add_result
  when: not ssh_key_already_added
  # failed_when: "ssh_key_add_result.rc != 0"
