---
- set_fact:
    controller_github_personal_access_token: "{{ controller_op_secret }}"
  vars:
    op_vault_name: JoshFun
    op_secret_name: GitHubPersonalAccessToken
    op_secret_field: token
  no_log: true

- name: Fetch existing SSH keys from GitHub
  uri:
    url: "https://api.github.com/user/keys"
    method: GET
    headers:
      Authorization: "token {{ controller_github_personal_access_token }}"
    return_content: yes
  register: github_keys_response

- name: Add SSH key to GitHub
  uri:
    url: "https://api.github.com/user/keys"
    method: POST
    headers:
      Authorization: "token {{ controller_github_personal_access_token }}"
    body_format: json
    body:
      title: "{{ inventory_hostname }}"
      key: "{{ keygen.ssh_public_key }}"
    status_code: 201
  when: not ssh_key_exists
  vars:
    github_existing_keys: "{{ github_keys_response.json | map(attribute='key') | list }}"
    actual_ssh_key: "{{ keygen.ssh_public_key.split(' ')[0:2] | join(' ') }}"
    ssh_key_exists: "{{ actual_ssh_key in github_existing_keys }}"
