---
- name: Ensure secrets exist
  include_role:
    name: managed_generated_secret
  vars:
    managed_generated_secret_name: "{{ item }}"
  loop:
  - awx_postgres_auth_password
  - awx_admin_password
