---
- name: Ensure managed_vault_files directory exists with proper permissions
  ansible.builtin.file:
    state: directory
    path: "{{ managed_vault_directory_path }}"
    mode: u=rwx,g-rwx,o-rwx
  no_log: true

- name: Managed file stat {{ managed_vault_password_file_path }}
  stat:
    path: "{{ managed_vault_password_file_path }}"
  register: managed_vault_password_file
  
- name: Create random vault password file if one doesn't exist
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.password', '/dev/null chars=ascii_letters,digits,punctuation') }}"
    dest: "{{ managed_vault_password_file_path }}"
    mode: u+rw,og-rwx
  no_log: true
  when:
  - not managed_vault_password_file.stat.exists

- name: Ensure file has the correct permissions
  ansible.builtin.file:
    path: "{{ managed_vault_password_file_path }}"
    state: file
    mode: u=rw,g-rwx,o-rwx
  no_log: true