---
- name: Ensure secrets exists
  include_role:
    name: korbad.project_management.managed_secret
  vars:
    managed_secret_name: "{{ item }}"
  loop:
  - kubeconfig_username
  - kubeconfig_password
