- name: Query user for information
  include_role:
    name: korbad.secrets.prompt_terminal_for_user_secret
  vars:
    user_secret_name: "{{ managed_user_secret_name }}"
  when: 
  - managed_user_secret_value is undefined

- name: Create secret file
  ansible.builtin.copy:
    content: "{{ managed_user_secret_value }}"
    dest: "{{ managed_user_secret_path }}"
    mode: u+rw,og-rwx
  no_log: true
  vars:
    managed_user_secret_value: "{{ vars[managed_user_secret_name] }}"

- name: Encrypt (ansible-vault) managed secret {{ managed_user_secret_path }}
  command:
    cmd: ansible-vault encrypt {{ managed_user_secret_path }} --vault-password-file {{ managed_vault_password_file_path }}
  no_log: true