---
- name: Managed secret stat {{ managed_user_secret_path }}
  stat:
    path: "{{ managed_user_secret_path }}"
  register: managed_user_secret

- name: Create secret file if it doesn't exist
  include_tasks: create_and_encrypt.yml
  when: not managed_user_secret.stat.exists or managed_user_secret_overwrite|default(false,true)|bool
  
- name: Ensure fact exists with managed secret value
  set_fact:
    "{{ managed_user_secret_name }}": "{{ lookup('file', managed_user_secret_path) }}"
  no_log: true
