managed_secrets_dirname: managed_secrets
managed_secrets_path: "{{ (ansible_env.HOME, managed_secrets_dirname) | path_join }}"
quayio_username: "{{ lookup('file', managed_secrets_path+'/quayio_username') }}"
quayio_token: "{{ lookup('file', managed_secrets_path+'/quayio_token') }}"
