- name: Check GitHub authentication status
  ansible.builtin.shell:
    cmd: gh auth status
  register: gh_auth_status_result
  failed_when: false
  changed_when: false

- name: Authenticate with GitHub using gh CLI and web browser
  command:
    cmd: gh auth login -h github.com -w -p ssh
  environment:
    DISPLAY: "{{ ansible_env.DISPLAY | default(':0', true) }}"
  when: gh_auth_status_result.rc == 1
  register: gh_auth_result

- name: Wait for authentication to complete
  ansible.builtin.shell:
    cmd: gh auth status
  register: gh_auth_status_result
  until: gh_auth_status_result.rc == 0
  retries: 60
  delay: 10
  failed_when: false
  changed_when: False