---
- hosts: localhost
  gather_facts: true
  vars:
    ansible_user: "{{ lookup('env','USER') }}"
    ansible_connection: local
  vars_prompt:
  - name: bitbucket_http_api_token
    prompt: bitbucket http api token?
    private: true
  roles:
  - name: korbad.project_management.managed_secret
    vars:
      managed_secret_value: "{{ bitbucket_http_api_token }}"
      managed_secret_overwrite: true
      managed_secret_name: bitbucket_http_api_token