---
- name: Ensure secrets exist
  include_role:
    name: korbad.project_management.managed_secret
  vars:
    managed_secret_name: "{{ item }}"
  loop:
  - awx_postgres_auth_password
  - awx_admin_password
